name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to Azure VM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 13.70.44.146
          username: azureuser
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          script: |
            cd testCICD/CI-cd
            node -v
            ls
            git pull origin main
            npm install
            node index.js